CREATE TABLE CARTE
(
  ID      INTEGER AUTO_INCREMENT,
  COULEUR VARCHAR(255),
  NOM     VARCHAR(255),
  VALEUR  INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE MAIN
(
  ID          INTEGER AUTO_INCREMENT,
  NOM_JOUEUR  VARCHAR(255),
  PRIMARY KEY (ID)
);


CREATE TABLE MAIN_CARTE
(
  ID_MAIN   INTEGER,
  ID_CARTE  INTEGER,
  FOREIGN KEY (ID_MAIN) REFERENCES MAIN (ID),
  FOREIGN KEY (ID_CARTE) REFERENCES CARTE (ID)
);

CREATE TABLE PARTIE (
  ID              INTEGER,
  ID_MAIN_JOUEUR  INTEGER,
  ID_MAIN_ADV     INTEGER,
  NB_CARTES       INTEGER,
  FOREIGN KEY (ID_MAIN_JOUEUR) REFERENCES MAIN (ID),
  FOREIGN KEY (ID_MAIN_ADV) REFERENCES MAIN (ID),
  PRIMARY KEY (ID)
);


CREATE TABLE TOUR (
  ID              INTEGER,
  ID_PARTIE       INTEGER,
  ID_CARTE_JOUEUR INTEGER,
  ID_CARTE_ADV    INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE TOUR_CARTES(
  ID_TOUR   INTEGER,
  ID_CARTE  INTEGER,
  FOREIGN KEY (ID_TOUR) REFERENCES TOUR (ID),
  FOREIGN KEY (ID_CARTE) REFERENCES CARTE (ID),

)